name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      # Uncomment for Vercel CLI deploy (requires secrets)
      # - run: npm i -g vercel@latest
      # - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
